### ISSUE TITLE
Change dependency from intl ^0.16.0.  to intl ^0.17.0

### ISSUE THREAD

**Issue by RobertoOFonseca** [weldonsouza/flutter_credit_card_detector#2]
"Because every version of flutter_credit_card_detector depends on intl ^0.16.0 and nextmed depends on intl ^0.17.0, flutter_credit_card_detector is forbidden."

All other packages that depended on intl ^0.16.0  now depends on   intl ^0.17.0

**Comment by weldonsouza** [comment]
is in the update process

**Comment by weldonsouza** [comment]
plugin updated to null safety version
