### ISSUE TITLE
Provider 6.0.0

### ISSUE THREAD

**Issue by joaohenriquesouza80** [weldonsouza/flutter_credit_card_detector#4]
Olá,

Bem legal esse seu package.
Teria como atualizar a versão do Provider?

`Because flutter_credit_card_detector >=2.0.0 depends on provider ^5.0.0 and flutter_credit_card_detector <2.0.0 depends on provider ^4.0.4, every version of flutter_credit_card_detector requires provider ^4.0.4 or ^5.0.0.
`
Muito obrigado,

**Comment by weldonsouza** [comment]
Bom dia!
package atualizado.
